name: Test and Benchmark

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Run Tests and Benchmarks
    runs-on: ubuntu-latest
    steps:

      - name: Get commit message header
        id: get_commit_message
        run: |
          COMMIT_MESSAGE_HEADER=$(git log -1 --pretty=%B | head -n 1)
          echo "COMMIT_MESSAGE_HEADER=${COMMIT_MESSAGE_HEADER}" >> $GITHUB_ENV
          
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for comparing benchmarks
      
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      
      - name: Run tests
        run: cargo test --verbose

      
      - name: Run benchmarks
        run: |
          mkdir -p benchmark_results
          cargo run --release -- benchmark benchmark_results/$COMMIT_MESSAGE_HEADER_latest.csv
      
      - name: Save benchmark results
        uses: actions/upload-artifact@v3
        with:
          name: benchmark-results
          path: benchmark_results/latest.csv
          retention-days: 90
